---
- hosts: ipa
  strategy: free 
  gather_facts: False
  become: true
  tasks:
  - name: Setting Hostname
    command: hostnamectl set-hostname ipa.test.example.com
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.20 ipa.test.example.com ipa
      create: yes
  - name: Adding Repo address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.19 repo.test.example.com repo
      create: yes
  - name: Adding system1 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.21 system1.test.example.com system1
      create: yes
  - name: Adding system2 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.22 system2.test.example.com system2
      create: yes
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.20/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search example.com ipv4.method manual
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloaded Firewall. Installing Environment Packages...
    command: firewall-cmd --reload
  - name: Packages Installed. Configuring IPA server...(Est. Time - 7 minutes)
    yum:
      name:
        - ipa-server
        - ipa-server-dns
        - vsftpd
      state: present
  - name: IPA server Configured.
    command: ipa-server-install --setup-dns --allow-zone-overlap --auto-reverse -a 'password' --hostname ipa.test.example.com -r TEST.EXAMPLE.COM -p 'password' -n test.example.com -U --forwarder 8.8.8.8
    ignore_errors: yes
  - name: Enabling services
    service: name={{item}} enabled=true
    with_items:
      - httpd
      - vsftpd
      - firewalld
  - name: Setting SELinux To Permissive
    shell: setenforce 0
  - name: Generating RSA Key
    command : ssh-keygen -q -t rsa -f /home/vagrant/.ssh/id_rsa -C "" -N ""
    become: yes
    become_user: vagrant
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #             _         _         _          
         #           /\ \      /\ \      / /\        
         #           \ \ \    /  \ \    / /  \       
         #           /\ \_\  / /\ \ \  / / /\ \      
         #          / /\/_/ / / /\ \_\/ / /\ \ \     
         #         / / /   / / /_/ / / / /  \ \ \    
         #        / / /   / / /__\/ / / /___/ /\ \   
         #       / / /   / / /_____/ / /_____/ /\ \  
         #   ___/ / /__ / / /     / /_________/\ \ \ 
         #  /\__\/_/___/ / /     / / /_       __\ \_\
         #  \/_________\/_/      \_\___\     /____/_/
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into `hostname`
         # This system is running `cat /etc/redhat-release`
         # kernel is `uname -r`
         #
         # You are logged in as `whoami`
         #
         "