---
- name: Setting up the IPA Server
  hosts: ipa
  strategy: free 
  gather_facts: False
  ignore_errors: true
  tasks:
  - name: Setting Hostname
    hostname: name=ipa.test.example.com
  - name: Building host file
    copy:
      dest: /etc/hosts
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n192.168.55.19 repo.test.example.com repo\n192.168.55.20 ipa.test.example.com ipa\n192.168.55.21 system1.test.example.com system1\n192.168.55.22 system2.test.example.com system2"
      force: yes
  - name: Configuring network
    command: nmcli con mod "System eth1" ipv4.addresses 192.168.55.20/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search test.example.com ipv4.method manual
  - name: Starting Firewalld
    service: 
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - firewalld
      - NetworkManager
  - name: Enabling Firewall Services
    firewalld: 
      service: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: yes
    with_items:
      - http 
      - https 
      - ntp 
      - dns 
      - kerberos 
      - ldap 
      - ldaps 
      - ftp
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/rpms.repo
      state: touch
      mode: 0755
  - name: Building Repo File then Installing Packages...
    copy:
      dest: /etc/yum.repos.d/rpms.repo
      content: "[rpms]\nname=rpms\nbaseurl=http://repo/rpms\ngpgcheck=0\nenabled=1"
      force: yes
  - name: Packages Installed. Configuring IPA server...(Est. Time - 7 minutes)
    yum: 
      name: "{{ item }}"
      state: latest
    with_items:
      - vsftpd
      - ipa-server 
      - ipa-server-dns 
      - chrony
  - name: Configuring IPA Server
    block:
      - name: IPA server Configured.
        command: ipa-server-install --setup-dns --allow-zone-overlap --auto-reverse -a 'password' --hostname ipa.test.example.com -r TEST.EXAMPLE.COM -p     'password' -n test.example.com -U --forwarder 8.8.8.8
    rescue:
      - debug: 
          msg: 'An error occurred during the IPA server configuration, reverting back...'
      - name: Reverting IPA Server config
        command: ipa-server-install --uninstall
  - name: Authenticating KRB5 Database
    expect:
      command: kinit admin
      responses:
        (.*)Password for admin@TEST.EXAMPLE.COM(.*): 'password'
  - name: Setting IPA user home directory location
    command: ipa config-mod --homedirectory /home/ldap
  - name: Enabling Services
    service: 
      name: "{{ item }}"
      enabled: true
      state: started
    with_items:
      - httpd
      - vsftpd
      - firewalld
      - chronyd
  - name: Generating RSA Key
    command : ssh-keygen -q -t rsa -f /home/vagrant/.ssh/id_rsa -C "" -N ""
    become: yes
    become_user: vagrant
    ignore_errors: yes
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #             _         _         _          
         #           /\ \      /\ \      / /\        
         #           \ \ \    /  \ \    / /  \       
         #           /\ \_\  / /\ \ \  / / /\ \      
         #          / /\/_/ / / /\ \_\/ / /\ \ \     
         #         / / /   / / /_/ / / / /  \ \ \    
         #        / / /   / / /__\/ / / /___/ /\ \   
         #       / / /   / / /_____/ / /_____/ /\ \  
         #   ___/ / /__ / / /     / /_________/\ \ \ 
         #  /\__\/_/___/ / /     / / /_       __\ \_\
         #  \/_________\/_/      \_\___\     /____/_/
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into \"`hostname`\" as the \"`whoami`\" account.
         # This system is running `cat /etc/redhat-release`
         #
         "