---
- hosts: ipa
  strategy: free
  gather_facts: False
  become: true
  tasks:
  - ipa_dnsrecord:
      ipa_host: ipa.test.example.com
      ipa_pass: password
      state: present
      zone_name: test.example.com
      record_name: system1
      record_type: 'A'
      record_value: '192.168.55.21'
    ignore_errors: true
  - name: Adding NFS service to System1
    ipa_service:
      name: nfs/system1.test.example.com
      state: present
      ipa_host: ipa.test.example.com
      ipa_user: admin
      ipa_pass: password 
  - name: Adding IPA user 'dave'
    ipa_user:
        name: dave
        state: present
        krbpasswordexpiration: 20200119235959
        givenname: dave
        sn: dave
        mail:
        - dave@test.example.com
        telephonenumber:
        - '+555123456'
        sshpubkey:
        password: password
        uidnumber: 1000
        gidnumber: 100
        ipa_host:  ipa.test.example.com
        ipa_user: admin
        ipa_pass: password
  - name: Adding IPA user 'lisa'
    ipa_user:
        name: lisa
        state: present
        krbpasswordexpiration: 20200119235959
        givenname: lisa
        sn: lisa
        mail:
        - lisa@test.example.com
        telephonenumber:
        - '+555123456'
        sshpubkey:
        password: password
        uidnumber: 1001
        gidnumber: 101
        ipa_host:  ipa.test.example.com
        ipa_user: admin
        ipa_pass: password    
  - name: Sending Key to System1
    expect:
      command: ssh-copy-id -i /home/vagrant/.ssh/id_rsa.pub vagrant@system1.test.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'Password': 'vagrant'
        '\]\$': 'logout'
        "vagrant@system1.test.example.com's password": 'vagrant'
      timeout: 10
    become: yes
    become_user: vagrant
    ignore_errors: yes
  - name: Sending Key to System2
    expect:
      command: ssh-copy-id -i /home/vagrant/.ssh/id_rsa.pub vagrant@system2.test.example.com 
      responses:
        'Are you sure you want to continue connecting': 'yes'
        'Password': 'vagrant'
        '\]\$': 'logout'
        "vagrant@system2.test.example.com's password": 'vagrant'
      timeout: 10
    become: yes
    become_user: vagrant
    ignore_errors: yes
  - name: Authenticating KRB5 Database
    expect:
      command: kinit admin
      responses:
        (.*)Password for admin@TEST.EXAMPLE.COM(.*): "password"
    tags: kerberos
  - name: Adding System1 NFS Principal to Keytab
    command: sudo kadmin.local ktadd nfs/system1.test.example.com
    tags: kerberos
  - name: Adding System1 Host Principal to Keytab
    command: sudo kadmin.local ktadd host/system1.test.example.com
    tags: kerberos
  - name: Copying Keytab To Apache Server
    command: cp /etc/krb5.keytab /var/www/html/system.keytab
  - name: Adjusting Permissions
    command: chmod 0644 /var/www/html/system.keytab
  - name: Copying Keytab To Apache Server
    command: cp /etc/krb5.keytab /var/www/html/system.keytab
  - name: Adjusting Permissions
    command: chmod 0644 /var/www/html/system.keytab
  - name: Welcome to the RHCE 7 Study/Test Environment!
    debug:
      msg:
        - 'Next Steps: Accessing The Systems:'
        - '- IPA - 192.168.55.20'
        - '- System 1 - 192.168.55.21'
        - '- System 2 - 192.168.55.22'
        - '- Username/Password - vagrant/vagrant'
        - '- For root - use `sudo` or `sudo su`'
        - '- Access example - `ssh vagrant@192.168.55.21` or `vagrant ssh system1`'
        - '- Happy Studying!'