---
- hosts: system1
  strategy: free
  gather_facts: False
  become: true
  tasks:
#  - name: Changing User Password
#    shell: echo vagrant | sudo passwd vagrant --stdin
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/ipa.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    blockinfile:
      dest: /etc/yum.repos.d/ipa.repo
      block: |
       [ipa]
       name=ipa repo
       baseurl=http://reflector.westga.edu/repos/CentOS/7/os/x86_64/
       gpgcheck=1
       gpgkey=http://reflector.westga.edu/repos/CentOS/7/os/x86_64/RPM-GPG-KEY-CentOS-7
       enabled=1
    tags: repo
  - name: Disabling services
    selinux:
      state: disabled
#  - name: Passively Disabling SELinux
#    shell: setenforce 0
#    ignore_errors: true
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.20  ipa.test.example.com ipa
      create: yes
  - name: Adding Repo address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.19  repo.test.example.com repo
      create: yes
  - name: Adding system1 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.21 system1.test.example.com system1
      create: yes
  - name: Adding system2 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.22 system2.test.example.com system1
      create: yes
  - name: Configuring network
    command: nmcli con mod "System enp0s8" ipv4.addresses "192.168.55.21/24 192.168.55.1" ipv4.dns 192.168.55.20 ipv4.dns-search test.example.com ipv4.method manual
#  - name: Saving network config
#    command: nmcli con up "System enp0s8" 
  - name: Fixing Resolv File
    command: echo 'nameserver 192.168.55.20' > /etc/resolv.conf
  - name: Authconfig Enabled. Installing Environment Packages...
    command: authconfig --update --enablesssd --enablesssdauth --enablemkhomedir
  - name: Environment Packages Installed. Configuring IPA Client...
    command: yum install -y ipa-client man-pages
#    async: 500
#    poll: 0
#    register: yum_sleeper
#  - name: Finishing Environment Package Installation Before IPA Client Configuration
#    async_status: jid={{ yum_sleeper.ansible_job_id }}
#    register: job_result
#    until: job_result.finished
#    retries: 40  
  - name: Configuring IPA client
    command: ipa-client-install --enable-dns-updates --force-join --mkhomedir --principal admin --server  ipa.test.example.com -w password --hostname system1.test.example.com --realm TEST.EXAMPLE.COM --domain test.example.com -U
    ignore_errors: yes
    async: 500
    poll: 0
    register: ipa_sleeper
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
    tags: repo
  - name: Enabling services
    service: name=firewalld enabled=true
  - name: Starting services
    service: name=firewalld state=started
  - name: Finishing IPA client configuration
    async_status: jid={{ ipa_sleeper.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 40
#  - name: Rebooting machine
#    reboot:
#      reboot_timeout: 60
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #          _     _        _        _         _           _          _   _        _             
         #         / /\  /\ \     /\_\     / /\      /\ \        /\ \       /\_\/\_\ _   / /\           
         #        / /  \ \ \ \   / / /    / /  \     \_\ \      /  \ \     / / / / //\_\/ /  \          
         #       / / /\ \_\ \ \_/ / /    / / /\ \__  /\__ \    / /\ \ \   /\ \/ \ \/ / /_/ /\ \         
         #      / / /\ \___\ \___/ /    / / /\ \___\/ /_ \ \  / / /\ \_\ /  \____\__/ /\_\/\ \ \        
         #      \ \ \ \/___/\ \ \_/     \ \ \ \/___/ / /\ \ \/ /_/_ \/_// /\/________/      \ \ \       
         #       \ \ \       \ \ \       \ \ \    / / /  \/_/ /____/\  / / /\/_// / /        \ \ \      
         #   _    \ \ \       \ \ \  _    \ \ \  / / /     / /\____\/ / / /    / / /          \ \ \     
         #  /_/\__/ / /        \ \ \/_/\__/ / / / / /     / / /______/ / /    / / /          __\ \ \___ 
         #  \ \/___/ /          \ \_\ \/___/ / /_/ /     / / /_______\/_/    / / /          /___\_\/__/\
         #   \_____\/            \/_/\_____\/  \_\/      \/__________/       \/_/           \_________\/
         '"#
         # You are logged into `hostname` as the `whoami` user
         # This system is running `cat /etc/redhat-release`
         # kernel is `uname -r`
         #
         # For root - use \`sudo\` or \`sudo su -\`
         # Repo is available to use from http://repo.test.example.com/rpms
         # Keytab is provided on http://ipa.test.example.com/system.keytab
         #
         # TEST.EXAMPLE.com realm has been configured already, there are also two additional NICs.
         # 
         # LDAP Users (Can be easily accessed from root user)
         # Usernames = dave, lisa
         # Passwords = password
         "
...